apiVersion: v1
kind: Pod
metadata:
    name: mypod
    labels:
       app: mypod
spec:
   containers:
       - name: mypod
         image: bhasmeht/myimage3
         ports:
            - containerPort: 8080
       
